feat: add log, error function

diff --git a/ithacli b/ithacli
--- a/ithacli
+++ b/ithacli
@@ -26,9 +26,9 @@ ithacli_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Install and configure all tools automatically\n" "setup"
-  printf "  %s   List of configurations that can be applied.\n" "list "
-  printf "  %s   Apply configurations.\n" "apply"
+  printf "  %s   List of configurations that can be applied.\n" "list  "
+  printf "  %s   Apply configurations.\n" "apply "
+  printf "  %s   Remove configurations.\n" "remove"
   echo
 
   # :command.long_usage
@@ -41,45 +41,6 @@ ithacli_usage() {
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
-    echo
-
-  fi
-}
-
-# :command.usage
-ithacli_setup_usage() {
-  printf "ithacli setup - Install and configure all tools automatically\n\n"
-  printf "Alias: st\n"
-  echo
-
-  printf "%s\n" "Usage:"
-  printf "  ithacli setup [OPTIONS]\n"
-  printf "  ithacli setup --help | -h\n"
-  echo
-
-  # :command.long_usage
-  if [[ -n $long_usage ]]; then
-    printf "%s\n" "Options:"
-
-    # :command.usage_flags
-    # :flag.usage
-    printf "  %s\n" "--overwrite, -w"
-    printf "    Overwrite existing configuration.\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "--backup, -b"
-    printf "    Backup existing configuration.\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "--skip, -s"
-    printf "    Skip existing configuration.\n"
-    echo
-
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
     echo
 
   fi
@@ -151,6 +112,48 @@ ithacli_apply_usage() {
     printf "%s\n" "Examples:"
     printf "  ithacli apply nvim\n"
     printf "  ithacli apply zsh --overwrite\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+ithacli_remove_usage() {
+  printf "ithacli remove - Remove configurations.\n\n"
+  printf "Alias: rm\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  ithacli remove SOURCE [OPTIONS]\n"
+  printf "  ithacli remove --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--user, -u USER (required)"
+    printf "    Username to use for logging in\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--password, -p PASSWORD"
+    printf "    Password to use for logging in\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "SOURCE"
+    printf "    File to upload\n"
     echo
 
   fi
@@ -228,25 +231,27 @@ inspect_args() {
   fi
 }
 
-# :command.command_functions
-# :command.function
-ithacli_setup_command() {
-  # src/setup_command.sh
-  echo "# this file is located in 'src/setup_command.sh'"
-  echo "# code for 'ithacli setup' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
-
+# :command.user_lib
+# src/lib/logging.sh
+function error() {
+	echo >&2 "[$(date +'%Y-%m-%dT%H:%M:%S')] ERROR: $1"
+	shift
+	for msg in "$@"; do echo >&2 "  $msg"; done
+	exit 1
+}
+function log() {
+	if ! [[ ${args[--quiet]} || $ITHACLI_QUIET ]]; then
+		echo >&2 "[$(date +'%Y-%m-%dT%H:%M:%S')] $1"
+		shift
+		for msg in "$@"; do echo >&2 "  $msg"; done
+	fi
 }
 
+# :command.command_functions
 # :command.function
 ithacli_list_command() {
   # src/list_command.sh
-  #!/bin/bash
-
-  # Directory to search for configurations
   directory="."
-
   # List of folder names to ignore
   ignore_list=("src" "fonts")
 
@@ -262,27 +267,35 @@ ithacli_list_command() {
   }
 
   # List configurations
-  if [[ -d "$directory" ]]; then
-  	printf "Available configurations:\n"
-  	for config in "$directory"/*; do
-  		if [[ -d "$config" ]]; then
-  			config_name=$(basename "$config")
-  			if ! is_ignored "$config_name"; then
-  				printf "  - %s\n" "$config_name"
-  			fi
+  log "Available configurations"
+  for config in "$directory"/*; do
+  	if [[ -d "$config" ]]; then
+  		config_name=$(basename "$config")
+  		if ! is_ignored "$config_name"; then
+  			printf "  - %s\n" "$config_name"
   		fi
-  	done
-  else
-  	echo "Error: Directory '$directory' not found"
-  fi
+  	# else
+  	# 	error "Configurations directory not found."
+  	fi
+  done
 
 }
 
 # :command.function
 ithacli_apply_command() {
   # src/apply_command.sh
-  echo "# this file is located in 'src/apply_command.sh'"
-  echo "# code for 'ithacli apply' goes here"
+  echo "# this file is located in 'src/remove_command.sh'"
+  echo "# code for 'ithacli remove' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
+
+}
+
+# :command.function
+ithacli_remove_command() {
+  # src/remove_command.sh
+  echo "# this file is located in 'src/remove_command.sh'"
+  echo "# code for 'ithacli remove' goes here"
   echo "# you can edit it freely and regenerate (it will not be overwritten)"
   inspect_args
 
@@ -317,13 +330,6 @@ parse_requirements() {
   case $action in
     -*) ;;
 
-    setup | st)
-      action="setup"
-      shift
-      ithacli_setup_parse_requirements "$@"
-      shift $#
-      ;;
-
     list | ls)
       action="list"
       shift
@@ -335,6 +341,13 @@ parse_requirements() {
       action="apply"
       shift
       ithacli_apply_parse_requirements "$@"
+      shift $#
+      ;;
+
+    remove | rm)
+      action="remove"
+      shift
+      ithacli_remove_parse_requirements "$@"
       shift $#
       ;;
 
@@ -355,73 +368,6 @@ parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-
-      -?*)
-        printf "invalid option: %s\n" "$key" >&2
-        exit 1
-        ;;
-
-      *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
-
-        ;;
-
-    esac
-  done
-
-}
-
-# :command.parse_requirements
-ithacli_setup_parse_requirements() {
-  # :command.fixed_flags_filter
-  while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
-      --help | -h)
-        long_usage=yes
-        ithacli_setup_usage
-        exit
-        ;;
-
-      *)
-        break
-        ;;
-
-    esac
-  done
-
-  # :command.command_filter
-  action="setup"
-
-  # :command.parse_requirements_while
-  while [[ $# -gt 0 ]]; do
-    key="$1"
-    case "$key" in
-      # :flag.case
-      --overwrite | -w)
-
-        # :flag.case_no_arg
-        args['--overwrite']=1
-        shift
-        ;;
-
-      # :flag.case
-      --backup | -b)
-
-        # :flag.case_no_arg
-        args['--backup']=1
-        shift
-        ;;
-
-      # :flag.case
-      --skip | -s)
-
-        # :flag.case_no_arg
-        args['--skip']=1
-        shift
-        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -557,6 +503,96 @@ ithacli_apply_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+ithacli_remove_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        ithacli_remove_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="remove"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --user | -u)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--user']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--user requires an argument: --user, -u USER" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --password | -p)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--password']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--password requires an argument: --password, -p PASSWORD" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['source']+x} ]]; then
+          args['source']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['source']+x} ]]; then
+    printf "missing required argument: SOURCE\nusage: ithacli remove SOURCE [OPTIONS]\n" >&2
+
+    exit 1
+  fi
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--user']+x} ]]; then
+    printf "missing required flag: --user, -u USER\n" >&2
+    exit 1
+  fi
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -576,9 +612,9 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
-    "setup") ithacli_setup_command ;;
     "list") ithacli_list_command ;;
     "apply") ithacli_apply_command ;;
+    "remove") ithacli_remove_command ;;
   esac
 }
 
